version: "1.0"
services:
  pyflink:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
  react:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 3000:3000
  
